app.py
from flask import Flask
from views import views, csrf
import os


def create_app():
    app = Flask(__name__)
    app.register_blueprint(views)
    csrf.init_app(app)
    app.secret_key = os.getenv('SECRET_KEY')

    return app

# Exposing so can be picked up by Zappa
app = create_app()

if __name__ == "__main__":
    import sys
    app = create_app()
    try:
        port = int(sys.argv[1])
    except (IndexError, ValueError):
        port = 5000
    app.run(debug=True, port=port)

views.py
import os
from functools import wraps
from datetime import date
import boto3
from botocore.client import Config
import flask
import json
from flask import (Blueprint, Response, redirect, render_template, request,
    current_app, jsonify, session, url_for)
from flask_wtf.csrf import CSRFProtect
from utils import LoginForm, is_safe_url

csrf = CSRFProtect()
views = Blueprint('views', __name__)


ZAPPA_HOST = os.getenv('ZAPPA_HOST')
S3_BUCKET = os.getenv('S3_BUCKET')
s3 = boto3.resource('s3')
s3_client = boto3.client(
    's3',
    region_name=os.getenv('AWS_REGION'),
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    aws_session_token=os.getenv('AWS_SESSION_TOKEN'),
    config=Config(signature_version='s3v4')
)
WATSON_URL = 'https://stream.watsonplatform.net/speech-to-text/api/v1/'


def auth_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if session.get('logged_in', False):
            return func(*args, **kwargs)
        else:
            return redirect('{}?next={}'.format(url_for('views.login'), url_for('views.index')))
    return wrapper


@views.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        session['logged_in'] = True
        next = flask.request.args.get('next', '')
        if not is_safe_url(next):
            return flask.abort(400)
        return redirect(next or flask.url_for('views.index'))
    return render_template('login.html', form=form)


@views.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('views.login'))


@views.route('/')
@auth_required
def index():
    prefix = request.args.get('prefix', '')
    render_dict = {}

    # At top level, only list dates
    if not len(prefix):
        objects = s3_client.list_objects(Bucket=S3_BUCKET, Prefix=prefix, Delimiter='/')
        if objects.get('CommonPrefixes'):
            render_dict['prefixes'] = [obj['Prefix'] for obj in objects['CommonPrefixes']]
    else:
        objects = s3_client.list_objects(Bucket=S3_BUCKET, Prefix=prefix)
        keys = [obj['Key'] for obj in objects['Contents'] if not obj['Key'].endswith('/')]
        key_dicts = [{'recording': k} for k in filter(lambda x: '/recordings/' in x, keys)]
        for kd in key_dicts:
            kd['audio_url'] = s3_client.generate_presigned_url(
                ClientMethod='get_object',
                Params={'Bucket': S3_BUCKET, 'Key': kd['recording']}
            )
            csv_key = kd['recording'].replace('/recordings/', '/clean/') + '.csv'
            if csv_key in keys:
                kd['transcript'] = csv_key.split('/')[-1]
                kd['transcript_url'] = s3_client.generate_presigned_url(
                    ClientMethod='get_object',
                    Params={'Bucket': S3_BUCKET, 'Key': csv_key}
                )

            kd['recording'] = kd['recording'].split('/')[-1]
            file_ext = kd['recording'].split('.')[-1]
            if file_ext == 'wav':
                kd['filetype'] = 'audio/x-wav'
            else:
                kd['filetype'] = 'audio/' + file_ext
        render_dict['prefix_date'] = keys[0].split('/')[0]
        render_dict['keys'] = key_dicts

    return render_template('index.html', **render_dict)


@views.route('/callback/<string:audio_key>/results', methods=['GET', 'POST'])
@csrf.exempt
def callback_route(audio_key):
    # Responds to Watson callback setting
    # TODO: Implement solving challenge_string
    if request.method == 'GET':
        challenge_string = request.args.get('challenge_string')
        if challenge_string:
            return Response(request.args.get('challenge_string'), mimetype='text/plain')
        else:
            return Response('', mimetype='text/plain')
    elif request.method == 'POST':
        # Gets 'results' val if finished, uploads as JSON to S3 in separate dir
        post_vals = request.get_json()
        s3_client.put_object(
            Bucket=S3_BUCKET,
            Key='{}/results/{}.json'.format(date.today().strftime('%Y%m%d'), audio_key),
            Body=json.dumps(post_vals)
        )
        return jsonify({'message': 'Success'})


@views.route('/upload', methods=['GET', 'POST'])
@auth_required
def direct_upload():
    # Load required data from the request
    if request.method == 'GET':
        return render_template('upload.html')
    elif request.method == 'POST':
        form = dict(request.form)
        # Form keys are in list form, unpacking
        file_name = form['file-name'][0]
        file_type = form['file-type'][0]
        # Generate and return the presigned URL
        presigned_post = s3_client.generate_presigned_post(
            Bucket=S3_BUCKET,
            Key=file_name,
            Fields={"acl": "public-read", "Content-Type": file_type},
            Conditions=[{"Content-Type": file_type}],
            ExpiresIn=3600
        )

        return jsonify(presigned_post)


@views.route('/edit', methods=['GET', 'POST'])
@auth_required
def edit_transcription():
    if request.method == 'GET':
        prefix = request.args.get('prefix')
        recording = request.args.get('recording')
        if not prefix and recording:
            return redirect(flask.url_for('views.index'))

        transcript_file = recording + '.json'
        transcript_key = '{}/results/{}'.format(prefix, transcript_file)
        transcript_obj = s3_client.get_object(Bucket=S3_BUCKET, Key=transcript_key)
        transcript = json.loads(transcript_obj['Body'].read())

        results = transcript['results'][0]['results']
        result_list = []
        for result in results:
            r = result['alternatives'][0]
            result_list.append({
                'transcript': r['transcript'].replace('%HESITATION', ''),
                'start': r['timestamps'][0][1],
                'end': r['timestamps'][-1][2]
            })

        # Generating presigned url for audio playback
        audio_url = s3_client.generate_presigned_url(
            ClientMethod='get_object',
            Params={'Bucket': S3_BUCKET, 'Key': '{}/recordings/{}'.format(prefix, recording)}
        )
        return render_template('editor.html',
                               # prefix=prefix,
                               transcript_key=transcript_key,
                               audio_url=audio_url,
                               filetype='audio/' + recording.split('.')[-1],
                               results=result_list)

    elif request.method == 'POST':
        result_json = request.get_json()
        if not len(result_json['results']):
            return redirect(flask.url_for('views.index'))

        transcript_obj = s3_client.get_object(Bucket=S3_BUCKET, Key=result_json['transcript_key'])
        transcript = json.loads(transcript_obj['Body'].read())

        results = transcript['results'][0]['results']
        if len(results) != len(result_json['results']):
            return redirect(flask.url_for('views.index'))

        for idx, r in enumerate(results):
            r['alternatives'][0]['transcript'] = result_json['results'][idx]

        s3_client.put_object(
            Bucket=S3_BUCKET,
            Key=result_json['transcript_key'],
            Body=json.dumps(transcript)
        )

        return jsonify({'message': 'success'})

templates/editor.html
{% extends "index.html" %}
{% block content %}
<div class="row main">
    <div class="col-sm-10 col-sm-offset-1">
        <h1>Edit Transcript</h1>
        <div>
            <audio controls preload="auto">
                <source src="{{ audio_url }}" type="{{ filetype }}">
                Your browser does not support the audio tag.
            </audio>
        </div>
        {% for r in results %}
        <div class="row transcript">
            <div class="col-sm-10">
                <textarea class="transcript-item" data-start="{{ r.start }}" data-end="{{ r.end }}">{{ r.transcript }}</textarea>
            </div>
            <div class="col-sm-2">
                <button class="btn btn-primary transcript" data-start="{{ r.start }}" data-end="{{ r.end }}">Play</button>
            </div>
        </div>
        {%  endfor %}
        <div class="row transcript">
            <div class="col-sm-2">
                <button id="submitTranscript" name="submitTranscript" class="btn btn-primary">Submit</button>
            </div>
            <div class="col-sm-10">
                <div id="progress" style="display:none">
                    Updating...
                </div>
                <div id="success" class="alert alert-success" style="display:none;">
                    <strong>Transcript updated.</strong>
                </div>
                <div id="failure" class="alert alert-danger" style="display:none;">
                    <strong>Transcript update failed.</strong>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
var transcript_key = "{{ transcript_key }}";
var csrftoken = "{{ csrf_token() }}";
var ZAPPA_HOST = "{{ url_for('views.edit_transcription') }}";
</script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Watson Transcription</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <meta charset='utf-8' />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      {% block topnav %}
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('views.index') }}">Home</a></li>
            <li><a href="{{ url_for('views.direct_upload') }}">Upload</a></li>
          </ul>
          <span class="navbar-text" style="float:right;"><a href="{{ url_for('views.logout') }}">Logout</a></span>
        </div>
      </nav>
      {% endblock %}
      {% block content %}
      <div class="row main">
        <div class="col-md-10">
            <h1>Recordings</h1>
            {% if prefix_date %}
            <h3>{{ prefix_date }}</h3>
            {% endif %}
            {% if prefixes %}
            <ul class="list-group">
                {% for prefix in prefixes %}
                <li class="list-group-item"><a href="{{ url_for('views.index') }}?prefix={{prefix}}">{{prefix}}</a></li>
                {% endfor %}
            </ul>
            {% endif  %}

            {% if keys %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Recording</th>
                        <th>Transcript</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for key in keys %}
                    <tr>
                        <td>
                            <a href="{{ key.audio_url }}" download>{{ key.recording }}</a>
                            <audio controls preload="none">
                                <source src="{{ key.audio_url }}" type="{{ key.filetype }}">
                                Your browser does not support the audio tag.
                            </audio>
                        </td>
                        <td>
                            {% if key.transcript_url %}
                            <a href="{{ key.transcript_url }}">{{ key.transcript }}</a>
                            {% else %}
                            Processing...
                            {% endif %}
                        </td>
                        <td>
                            {% if key.transcript_url %}
                            <a class="btn btn-primary"
                               href="{{ url_for('views.edit_transcription') }}?prefix={{ prefix_date }}&recording={{ key.recording }}">
                                Edit
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
      </div>


      {% endblock %}
    </div>
  </body>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</html>

templates/login.html
{% extends "index.html" %}
{% block topnav %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Login</h1>
        <form role="form" action="{{ url_for('views.login') }}?next={{request.args.get('next', '')}}" method="post">
            {{form.hidden_tag()}}
            <div class="form-group">
                <label for="username">Username: </label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button id="submit" name="submit" type="submit" class="btn btn-primary">Login</button>
        </form>
     </div>
</div>
{% endblock %}

templates/upload.html
{% extends "index.html" %}
{% block content %}
<div class="row main">
    <div class="col-md-6 col-md-offset-3">
        <h1>Upload Recording</h1>
        <div class="form-group">
            <label for="recording">Recording: </label>
            <input type="file" class="form-control" id="recording" name="recording">
        </div>
        <div class="progress" id="progress" style="display:none;">
          <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="0"
               aria-valuemin="0" aria-valuemax="100" style="width:0">
          </div>
        </div>
        <div id="success" class="alert alert-success" style="display:none;">
            <strong>File uploaded.</strong>
        </div>
        <div id="failure" class="alert alert-danger" style="display:none;">
            <strong>File upload failed.</strong>
        </div>
        <button id="upload" name="upload" class="btn btn-primary">Upload</button>
     </div>
</div>
<script>
var csrftoken = "{{ csrf_token() }}";
var ZAPPA_HOST = "{{ url_for('views.direct_upload') }}";
</script>
{% endblock %}